#version: '3.8'

services:

  postgres-db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1232580
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: myapp:2.4
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_VERSION: 2.4.1
      SERVER_ADDR: 192.168.0.102:8080
      DB_USER: postgres
      DB_NAME: test
      DB_PASS: 1232580
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_SSLMODE: disable
    depends_on:
      - postgres-db
    

volumes:
  postgres_data: